name: Production Build
on: 
  push:
    branches: [main]
    tags: '*'
jobs:
  build_pages:
    #if: github.event_name == 'tags' # uncomment this to generate new builds only with new GH releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install && npm run build
        env:
         CI: ""
      - uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build
          clean-exclude: pr-preview/
          force: false
